export const GET_RECEIPTS = {
  START_REQUEST: 'GET_RECEIPTS_START_REQUEST',
  SUCCESS: 'GET_RECEIPTS_ITEMS',
  FAIL: 'GET_RECEIPTS_FAIL',
  NO_ITEMS: 'GOT_NO_ITEMS'
}

export const POST_COMMENT = {
  START_REQUEST: 'POST_COMMENT_START_REQUEST',
  SUCCESS: 'POSTED_COMMENT_SUCCESS',
  FAIL: 'POST_COMMENT_FAIL'
}

export const MODAL = {
  OPEN: 'OPEN_MODAL',
  CLOSE: 'CLOSE_MODAL'
}

export const POST_RECEIPT = {
  START_REQUEST: 'POST_RECEIPT_START_REQUEST',
  SUCCESS: 'POST_RECEIPT_SUCCESS',
  FAIL: 'POST_RECEIPT_FAIL'
}

export const TOGGLE_SAVE_BUTTON = 'TOGGLE_SAVE_BUTTON'

export const SORT_DATA = 'SORT_DATA'
