const GET_RECEIPTS_START_REQUEST = 'GET_RECEIPTS_START_REQUEST'
const GOT_RECEIPTS_SUCESS = 'GET_RECEIPTS_ITEMS'
const GET_FAIL = 'GET_RECEIPTS_FAIL'
const GOT_NO_ITEMS = 'GOT_NO_ITEMS'

export const RECEIPT = {
  GET_RECEIPTS_START_REQUEST,
  GOT_RECEIPTS_SUCESS,
  GET_FAIL,
  GOT_NO_ITEMS
}

const POST_COMMENT_START_REQUEST = 'POST_COMMENT_START_REQUEST'
const POSTED_COMMENT_SUCCESS = 'POSTED_COMMENT_SUCCESS'
const POST_COMMENT_FAIL = 'POST_COMMENT_FAIL'

export const COMMENT = {
  POST_COMMENT_START_REQUEST,
  POSTED_COMMENT_SUCCESS,
  POST_COMMENT_FAIL
}

export const MODAL = {
  OPEN: 'OPEN_MODAL',
  CLOSE: 'CLOSE_MODAL'
}

export const POST_RECEIPT = {
  START_REQUEST: 'POST_RECEIPT_START_REQUEST',
  SUCCESS: 'POST_RECEIPT_SUCCESS',
  FAIL: 'POST_RECEIPT_SUCCESS'
}
